version: '3.7'

services:
  app:
    image: flycompany/holdkamp
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug-confg.ini
      - ./setup/horizon.ini:/usr/local/etc/php/conf.d/docker-php-horizon.ini
    ports:
      - 80:80
    depends_on:
      - database
      - phpmyadmin
      - smtp
      - redis
      - worker

  worker:
    image: flycompany/holdkamp
    entrypoint: "php artisan queue:listen -vvv --timeout 600 --memory 512"
    user: "33:33"
    environment:
      TELESCOPE_ENABLED: "false"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
      - ./setup/horizon.ini:/usr/local/etc/php/conf.d/docker-php-horizon.ini
    depends_on:
      - database
      - phpmyadmin
      - smtp
      - redis

  artisan:
    image: flycompany/holdkamp
    user: "1000:33"
    entrypoint: "php artisan"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./setup/horizon.ini:/usr/local/etc/php/conf.d/docker-php-horizon.ini

  database:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: holdkamp
      MYSQL_USER: holdkamp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  ngrok:
    image: wernight/ngrok
    command: 'ngrok http app:80'
    ports:
      - 4040:4040

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8080:80

  redis:
    image: bitnami/redis:4.0
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  composer:
    image: composer:2
    user: "1000:1000"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

volumes:
  db-data:
    driver: local
