query cancellationCollector($id: ID!, $dateRange: Mixed){
    cancellationCollector(id: $id){
        id
        email
        cancellationPublic(first: 20, page: 0, hasDates: {column: DATE, operator: BETWEEN, value: $dateRange}){
            data{
                member {
                    id
                    name
                }
                dates {
                    date
                }
                message
                createdAt
            }
        }
        createdAt
        updatedAt
        sharingId
    }
}
