query me{
    me{
        id
        name
        email
        cancellationCollector {
            id
        }
        clubhouse{
            id
            email
            name
            cancellationCollector {
                id
            }
            clubs {
                id
                name1
                initialized
            }
        },
        clubhouses {
            id
        }
    }
}
