query teamRound($id: ID!, $scenarioId: ID){
    teamRound(id: $id){
        id
        squads{
            id
            playerLimit
            order
            name
            tier
            team{
                id
                name
                tier {
                    id
                    tierName
                }
                groupName
            }
            playingCity
            playingZipCode
            playingAddress
            playingPlace
            playingDatetime
            externalTeamFightID
            version
            categories(scenarioId: $scenarioId){
                id
                category
                name
                players{
                    id
                    gender
                    name
                    refId
                    vintage
                    parallelAllocation{
                        teamRoundId
                        teamRoundName
                        squadName
                        squadOrder
                        categoryName
                    }
                    points{
                        id
                        category
                        points
                        position
                        vintage
                        corrected_manually
                        version
                    }
                }
            }
        }
        name
        gameDate
        version
        round
        reachablePlayerRefIds
        scenarios {
            id
            name
            isOfficial
        }
        season {
            id
        }
    }
}
