name: Build

on:
  push:
    tags:
      - v*
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Frontend build
        run: |
          yarn install --frozen-lockfile
          yarn run production
          ls -lah public/css
          ls -lah public/js
          ls -lah public/images
          ls -lah public/mix-manifest.json

      - name: executing remote ssh commands using password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SIMPLY_SSH_HOST }}
          username: ${{ secrets.SIMPLY_SSH_USERNAME }}
          key: ${{ secrets.SIMPLY_SSH_KEY }}
          port: 22
          source: "public/css,public/js,public/images,public/mix-manifest.json"
          target: /var/www/badminton.social/testing
