name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: holdkamp_graphqltesting
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: holdkamp_graphqltesting
      DB_USERNAME: root
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - uses: php-actions/composer@v6
        with:
          php_version: 8.4
          version: 2
          args: --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate passport keys
        run: php artisan passport:keys
      - name: Execute tests (GraphQL tests) via PHPUnit
        run: php vendor/bin/phpunit --exclude-group remote
