name: Deployment

on:
  push:
    branchs:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          TEST_SECRET: ${{ secrets.SIMPLY_SSH_HOST }}
        run: echo $TEST_SECRET

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SIMPLY_SSH_HOST }}
          username: ${{ secrets.SIMPLY_SSH_USERNAME }}
          password: ${{ secrets.SIMPLY_SSH_PASSWORD }}
          key: ${{ secrets.SIMPLY_SSH_KEY }}
          debug: true
          script: whoami
